# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BreweryBess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'AARatingBar'
  pod 'Swinject'
  pod 'SDWebImage'
  pod 'RealmSwift'
  pod 'RxSwift'

  # Pods for BreweryBess

  target 'BreweryBessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreweryBessUITests' do
    # Pods for testing
  end

end
